export { AccountDetailsAsync as AccountDetailsPage } from './ui/subpages/AccountDetails/AccountDetails.async'
export { AccountDashboardAsync as Dashboard } from './ui/subpages/AccountDashboard/AccountDashboard.async'
export { AccountAddressesAsync as Addresses } from './ui/subpages/AccountAddresses/AccountAddresses.async'
export { AccountOrdersAsync as Orders } from './ui/subpages/AccountOrders/AccountOrders.async'
export { AccountWishlistAsync as Wishlist } from './ui/subpages/AccountWishlist/AccountWishlist.async'
export { default as ProfileLayout } from './ui/ProfileLayout/ProfileLayout'
