export { AccountDetailsPageAsync as AccountDetailsPage } from './ui/subpages/AccountDetails/AccountDetailsPage.async'
export { DashboardAsync as Dashboard } from './ui/subpages/Dashboard/Dashboard.async'
export { AddressesAsync as Addresses } from './ui/subpages/Addresses/Addresses.async'
export { OrdersAsync as Orders } from './ui/subpages/Orders/Orders.async'
export { WishlistAsync as Wishlist } from './ui/subpages/Wishlist/Wishlist.async'
export { default as ProfileLayout } from './ui/ProfileLayout/ProfileLayout'
