name: Linting, testing and building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: yarn
      - name: Build production project
        run: npm run build:prod
      - name: Linting Typescript
        run: npm run lint:ts
      - name: Linting CSS
        run: npm run lint:scss
      - name: Unit testing
        run: npm run test:unit
      - name: Build Storybook
        run: npm run storybook:build
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
